Repository ufcg-lsd/saps-engine, pull requests merged in 2020-04, with the labels that each got.

#110 Improvement/archiver doc
  config/archiver.conf
  docs/archiver-install.md
  docs/dispatcher-install.md
Labels: doc, enhancement

#120 Hot fix - add log messages in the authentication service
  src/main/java/org/fogbowcloud/saps/engine/core/dispatcher/restlet/resource/BaseResource.java
  src/main/java/org/fogbowcloud/saps/engine/core/dispatcher/restlet/resource/UserResource.java
Labels: enhancement

#123 Script for submit task (CLI)
  bin/submit-task
Labels: enhancement

#125 Bug / get digest
  src/main/java/org/fogbowcloud/saps/engine/core/dispatcher/SubmissionDispatcher.java
  src/main/java/org/fogbowcloud/saps/engine/core/dispatcher/restlet/DatabaseApplication.java
  src/main/java/org/fogbowcloud/saps/engine/core/dispatcher/restlet/resource/ImageResource.java
  src/main/java/org/fogbowcloud/saps/engine/core/dispatcher/utils/DigestUtil.java
Labels: bug, deletion

#126 Improvement/dispatcher doc
  docs/dispatcher-install.md
Labels: doc

#124 Feature/dockerfiles
  docker/context/catalog/init-catalog.sh
  docker/dockerfiles/archiver
  docker/dockerfiles/catalog
  docker/dockerfiles/dispatcher
  docker/dockerfiles/scheduler
  docker/stack.sh
Labels: enhancement, feature

#130 Doc / Arrebol worker
  docs/arrebol-worker.md
Labels: doc

#128 Cli / get all tasks
  bin/get-all-tasks
Labels: enhancement

#134 Feature/docker compose
  deploy/config/archiver.conf
  deploy/config/catalog.env
  deploy/config/dispatcher.conf
  deploy/config/execution_script_tags.json
  deploy/config/log4j.properties
  deploy/config/scheduler.conf
  deploy/deploy-stack.sh
  deploy/docker-compose.yml
Labels: enhancement, feature

#121 Doc/end to end test
  docs/end-to-end-test.md
  docs/img/end-to-end-test-check-results-img1.png
  docs/img/end-to-end-test-check-results-img2.png
  docs/img/end-to-end-test-flow.png
  docs/img/end-to-end-test-run-img1.png
  docs/img/end-to-end-test-run-img2.png
  docs/img/end-to-end-test-run-img3.png
  docs/img/end-to-end-test-run-img4.png
Labels: doc, test
